name: Daily Current Affairs Scraper

on:
  schedule:
    # Run every day at 7:30 AM IST (2:00 AM UTC)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape-and-generate:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Playwright
        run: |
          python -m playwright install chromium --with-deps
      
      - name: Create .env file
        run: |
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" > .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "ENGLISH_CHANNEL=${{ secrets.ENGLISH_CHANNEL }}" >> .env
          echo "GUJARATI_CHANNEL=${{ secrets.GUJARATI_CHANNEL }}" >> .env
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env
      
      - name: Get current month
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "MONTH=$(date +'%Y-%m')" >> $GITHUB_ENV
      
      - name: Run scraper for entire month
        env:
          MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ENGLISH_CHANNEL: ${{ secrets.ENGLISH_CHANNEL }}
          GUJARATI_CHANNEL: ${{ secrets.GUJARATI_CHANNEL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          python main.py --month ${{ env.MONTH }} --languages en gu --send-telegram --github-actions 